-- Seed criticality (1=low, 2=medium, 3=high) for all maintenance_templates.
UPDATE public.maintenance_templates SET criticality = 2 WHERE title = 'Replace HVAC filter';
UPDATE public.maintenance_templates SET criticality = 2 WHERE title = 'Schedule HVAC tune-up';
UPDATE public.maintenance_templates SET criticality = 2 WHERE title = 'Clean or replace humidifier pad';
UPDATE public.maintenance_templates SET criticality = 2 WHERE title = 'Vacuum refrigerator coils';
UPDATE public.maintenance_templates SET criticality = 2 WHERE title = 'Clean dryer vent';
UPDATE public.maintenance_templates SET criticality = 1 WHERE title = 'Clean dryer lint screen';
UPDATE public.maintenance_templates SET criticality = 2 WHERE title = 'Clean dishwasher filter and spray arms';
UPDATE public.maintenance_templates SET criticality = 2 WHERE title = 'Clean range hood filter';
UPDATE public.maintenance_templates SET criticality = 2 WHERE title = 'Run washing machine clean cycle';
UPDATE public.maintenance_templates SET criticality = 3 WHERE title = 'Test smoke alarms';
UPDATE public.maintenance_templates SET criticality = 3 WHERE title = 'Test CO detectors';
UPDATE public.maintenance_templates SET criticality = 3 WHERE title = 'Replace smoke alarm batteries';
UPDATE public.maintenance_templates SET criticality = 3 WHERE title = 'Check fire extinguisher';
UPDATE public.maintenance_templates SET criticality = 2 WHERE title = 'Flush water heater';
UPDATE public.maintenance_templates SET criticality = 3 WHERE title = 'Test water heater pressure relief valve';
UPDATE public.maintenance_templates SET criticality = 2 WHERE title = 'Check under sinks for leaks';
UPDATE public.maintenance_templates SET criticality = 1 WHERE title = 'Clean faucet aerators';
UPDATE public.maintenance_templates SET criticality = 3 WHERE title = 'Inspect sump pump';
UPDATE public.maintenance_templates SET criticality = 2 WHERE title = 'Clean gutters';
UPDATE public.maintenance_templates SET criticality = 2 WHERE title = 'Inspect roof';
UPDATE public.maintenance_templates SET criticality = 2 WHERE title = 'Inspect siding and caulk';
UPDATE public.maintenance_templates SET criticality = 2 WHERE title = 'Check foundation and basement';
UPDATE public.maintenance_templates SET criticality = 3 WHERE title = 'Test GFCI outlets';
UPDATE public.maintenance_templates SET criticality = 2 WHERE title = 'Inspect electrical panel';
UPDATE public.maintenance_templates SET criticality = 2 WHERE title = 'Replace furnace humidifier pad';
UPDATE public.maintenance_templates SET criticality = 2 WHERE title = 'Winterize outdoor faucets';
UPDATE public.maintenance_templates SET criticality = 2 WHERE title = 'Dewinterize irrigation';
UPDATE public.maintenance_templates SET criticality = 2 WHERE title = 'Service lawn mower';
UPDATE public.maintenance_templates SET criticality = 2 WHERE title = 'Inspect attic';
UPDATE public.maintenance_templates SET criticality = 2 WHERE title = 'Check caulk around tub and shower';
