-- Seed risks_of_skipping and benefits_of_maintenance for existing maintenance_templates.
-- Short, to-the-point content for each template.

UPDATE public.maintenance_templates SET risks_of_skipping = 'Poor airflow, higher bills, strain on blower; worse air quality.', benefits_of_maintenance = 'Better airflow and air quality; system lasts longer.' WHERE title = 'Replace HVAC filter';
UPDATE public.maintenance_templates SET risks_of_skipping = 'Unexpected breakdowns, lost efficiency, shorter system life.', benefits_of_maintenance = 'Catch issues early; extend life and keep efficiency.' WHERE title = 'Schedule HVAC tune-up';
UPDATE public.maintenance_templates SET risks_of_skipping = 'Low humidity, dry air, mineral buildup in unit.', benefits_of_maintenance = 'Proper moisture levels; unit runs clean and lasts longer.' WHERE title = 'Clean or replace humidifier pad';
UPDATE public.maintenance_templates SET risks_of_skipping = 'Fridge works harder, higher bills, shorter life.', benefits_of_maintenance = 'Runs cooler and more efficiently; extends life.' WHERE title = 'Vacuum refrigerator coils';
UPDATE public.maintenance_templates SET risks_of_skipping = 'Lint fire risk; longer dry times and wear.', benefits_of_maintenance = 'Reduces fire risk; faster drying and longer dryer life.' WHERE title = 'Clean dryer vent';
UPDATE public.maintenance_templates SET risks_of_skipping = 'Fire risk; longer dry times.', benefits_of_maintenance = 'Safer operation; faster drying.' WHERE title = 'Clean dryer lint screen';
UPDATE public.maintenance_templates SET risks_of_skipping = 'Poor cleaning, odors, clogs.', benefits_of_maintenance = 'Cleaner dishes; fewer clogs and odors.' WHERE title = 'Clean dishwasher filter and spray arms';
UPDATE public.maintenance_templates SET risks_of_skipping = 'Reduced airflow, grease buildup, fire risk.', benefits_of_maintenance = 'Better ventilation; lower fire risk.' WHERE title = 'Clean range hood filter';
UPDATE public.maintenance_templates SET risks_of_skipping = 'Odors, residue, mold in drum and hoses.', benefits_of_maintenance = 'Cleaner loads; fewer odors and buildup.' WHERE title = 'Run washing machine clean cycle';
UPDATE public.maintenance_templates SET risks_of_skipping = 'Dead batteries when you need them; no early warning.', benefits_of_maintenance = 'Reliable early warning in a fire.' WHERE title = 'Test smoke alarms';
UPDATE public.maintenance_templates SET risks_of_skipping = 'CO poisoning risk if detector fails.', benefits_of_maintenance = 'Reliable CO detection; peace of mind.' WHERE title = 'Test CO detectors';
UPDATE public.maintenance_templates SET risks_of_skipping = 'Alarms fail when needed; no warning in emergency.', benefits_of_maintenance = 'Alarms work when you need them.' WHERE title = 'Replace smoke alarm batteries';
UPDATE public.maintenance_templates SET risks_of_skipping = 'Extinguisher may not work when needed.', benefits_of_maintenance = 'Working extinguisher when you need it.' WHERE title = 'Check fire extinguisher';
UPDATE public.maintenance_templates SET risks_of_skipping = 'Sediment, corrosion, early failure; tank may last only ~6–10 yrs.', benefits_of_maintenance = 'Extend tank life from ~10 to 15–20 yrs; better efficiency.' WHERE title = 'Flush water heater';
UPDATE public.maintenance_templates SET risks_of_skipping = 'Tank can overpressurize; rupture or explosion risk.', benefits_of_maintenance = 'Pressure relief works in an emergency; safer tank.' WHERE title = 'Test water heater pressure relief valve';
UPDATE public.maintenance_templates SET risks_of_skipping = 'Small leaks become big; water damage, mold.', benefits_of_maintenance = 'Catch leaks early; avoid costly water damage.' WHERE title = 'Check under sinks for leaks';
UPDATE public.maintenance_templates SET risks_of_skipping = 'Low flow, sediment in water, worn aerator.', benefits_of_maintenance = 'Better flow; cleaner water at tap.' WHERE title = 'Clean faucet aerators';
UPDATE public.maintenance_templates SET risks_of_skipping = 'Pump may not run when needed; basement flooding.', benefits_of_maintenance = 'Sump works when it rains; avoid flooding.' WHERE title = 'Inspect sump pump';
UPDATE public.maintenance_templates SET risks_of_skipping = 'Overflow, roof leaks, foundation and siding damage.', benefits_of_maintenance = 'Water directed away; less rot and foundation issues.' WHERE title = 'Clean gutters';
UPDATE public.maintenance_templates SET risks_of_skipping = 'Leaks go unnoticed; costly repairs or replacement.', benefits_of_maintenance = 'Catch damage early; cheaper repairs.' WHERE title = 'Inspect roof';
UPDATE public.maintenance_templates SET risks_of_skipping = 'Water intrusion, rot, pests, drafts.', benefits_of_maintenance = 'Sealed envelope; less moisture and pests.' WHERE title = 'Inspect siding and caulk';
UPDATE public.maintenance_templates SET risks_of_skipping = 'Cracks and moisture lead to costly structural and mold issues.', benefits_of_maintenance = 'Catch cracks and moisture early; protect structure.' WHERE title = 'Check foundation and basement';
UPDATE public.maintenance_templates SET risks_of_skipping = 'Shock or fire if GFCI does not trip when it should.', benefits_of_maintenance = 'GFCIs trip when needed; safer outlets.' WHERE title = 'Test GFCI outlets';
UPDATE public.maintenance_templates SET risks_of_skipping = 'Overheating, fire, or repeated trips go unnoticed.', benefits_of_maintenance = 'Spot issues early; safer electrical system.' WHERE title = 'Inspect electrical panel';
UPDATE public.maintenance_templates SET risks_of_skipping = 'Low humidity, mineral buildup, pad stops working.', benefits_of_maintenance = 'Consistent humidity; unit lasts longer.' WHERE title = 'Replace furnace humidifier pad';
UPDATE public.maintenance_templates SET risks_of_skipping = 'Frozen pipes; burst pipes and water damage.', benefits_of_maintenance = 'Outdoor faucets and pipes survive winter.' WHERE title = 'Winterize outdoor faucets';
UPDATE public.maintenance_templates SET risks_of_skipping = 'Broken heads or leaks waste water; dead zones in lawn.', benefits_of_maintenance = 'Even coverage; no surprise leaks or dry spots.' WHERE title = 'Dewinterize irrigation';
UPDATE public.maintenance_templates SET risks_of_skipping = 'Hard starting, poor cut, more wear.', benefits_of_maintenance = 'Starts reliably; cleaner cut; longer mower life.' WHERE title = 'Service lawn mower';
UPDATE public.maintenance_templates SET risks_of_skipping = 'Leaks, pests, and poor insulation go unnoticed.', benefits_of_maintenance = 'Catch leaks and pests early; better insulation.' WHERE title = 'Inspect attic';
UPDATE public.maintenance_templates SET risks_of_skipping = 'Water behind walls; mold and rot.', benefits_of_maintenance = 'Water stays in tub; no hidden mold or rot.' WHERE title = 'Check caulk around tub and shower';
