-- Seed maintenance_templates with standard home maintenance tasks.
-- Inserts only when a template with the same title does not exist (no duplicates).
-- Category mapping: Safety->safety, HVAC->hvac, Plumbing->plumbing, Exterior->exterior, Electrical->electrical, Structure->interior.
-- Criticality: High=3, Medium=2, Low=1. Frequency: Monthly=30, Quarterly=90, Yearly=365, Twice yearly=182, 1-3 months=60.

INSERT INTO public.maintenance_templates (
  title,
  description,
  summary,
  instructions,
  category,
  frequency_days,
  criticality,
  risks_of_skipping,
  benefits_of_maintenance,
  repair_cost_savings
)
SELECT v.title, v.description, v.summary, v.instructions, v.category, v.frequency_days, v.criticality, v.risks_of_skipping, v.benefits_of_maintenance, v.repair_cost_savings
FROM (VALUES
  ('Test smoke detectors', 'Test all smoke detectors to ensure they sound when triggered.', 'Verify every smoke detector sounds during a test.', '1. Locate all smoke detectors. 2. Press and hold the test button until the alarm sounds. 3. Replace batteries or units that do not respond. 4. Test monthly.', 'safety', 30, 3, 'Non-working detectors delay escape and increase fire injury or death risk.', 'Early warning in a fire saves lives and reduces property loss.', 'Avoid fire-related injury, death, and major property damage.'),
  ('Test carbon monoxide detectors', 'Test CO detectors to ensure they alert to dangerous carbon monoxide levels.', 'Confirm CO detectors respond correctly.', '1. Find all CO detectors (often near bedrooms and fuel-burning appliances). 2. Press test button and confirm alarm. 3. Replace batteries or units as needed. 4. Test monthly.', 'safety', 30, 3, 'CO is odorless and deadly; faulty detectors can lead to poisoning or death.', 'Reliable detection prevents CO poisoning and fatalities.', 'Prevents CO poisoning; avoids emergency care and potential loss of life.'),
  ('Replace smoke/CO batteries', 'Replace batteries in all smoke and carbon monoxide detectors.', 'Swap batteries in all smoke and CO detectors once a year.', '1. Note detector locations. 2. Replace batteries with fresh ones (use same type). 3. Test each unit after replacement. 4. Mark calendar for next year.', 'safety', 365, 3, 'Dead batteries mean no alarm during fire or CO emergency.', 'Fresh batteries ensure detectors work when needed.', 'Ensures detectors function in an emergency; avoids battery-related failures.'),
  ('Inspect fire extinguishers', 'Check fire extinguishers for charge, damage, and accessibility.', 'Verify extinguishers are charged, visible, and not expired.', '1. Locate all extinguishers. 2. Check gauge (needle in green). 3. Inspect for damage or corrosion. 4. Confirm they are unobstructed and mounted correctly. 5. Replace or recharge if needed.', 'safety', 365, 3, 'Discharged or missing extinguishers reduce ability to control small fires.', 'Working extinguishers allow quick response to small fires.', 'Helps contain small fires and avoid major fire damage.'),
  ('Check GFCI outlets', 'Test GFCI outlets to ensure they trip and reset correctly.', 'Test all GFCIs so they trip and reset as designed.', '1. Find all GFCI outlets (kitchen, bath, garage, exterior). 2. Press TEST; outlet should cut power. 3. Press RESET to restore. 4. If they do not trip or reset, replace or call an electrician.', 'safety', 90, 3, 'Faulty GFCIs increase risk of shock or electrocution near water.', 'Proper GFCIs prevent shock in wet areas.', 'Reduces shock risk and potential injury or code violations.'),
  ('Clean dryer vent', 'Remove lint and debris from the dryer vent and duct to prevent fire.', 'Clear dryer vent and duct for safe airflow.', '1. Disconnect duct from dryer. 2. Remove lint from duct and vent cap. 3. Use a brush or vacuum made for dryer vents. 4. Reconnect and run a short cycle to confirm airflow.', 'safety', 90, 3, 'Clogged vents cause overheating and are a leading cause of dryer fires.', 'Clear vents reduce fire risk and improve drying efficiency.', 'Lowers fire risk and can extend dryer life.'),
  ('Inspect dryer exhaust duct', 'Inspect the full dryer exhaust run for damage, leaks, or blockages.', 'Check the entire dryer exhaust path once a year.', '1. Follow duct from dryer to exterior. 2. Check for kinks, holes, or loose connections. 3. Ensure exterior cap opens and is not blocked. 4. Clean or repair as needed.', 'safety', 365, 3, 'Damaged or blocked ducts increase fire risk and reduce dryer performance.', 'A clear, intact duct improves safety and drying.', 'Reduces fire risk and improves dryer efficiency.'),
  ('Test garage door auto reverse', 'Test the garage door auto-reverse so it stops and reverses on obstruction.', 'Verify door reverses when it hits an obstruction.', '1. Place a roll of paper towels or similar object in the door path. 2. Close the door from the opener. 3. Door should stop and reverse on contact. 4. Adjust sensitivity per manufacturer if needed.', 'safety', 90, 3, 'Failing auto-reverse can trap or injure people or pets.', 'Working auto-reverse prevents entrapment and injury.', 'Reduces risk of entrapment and injury.'),
  ('Check window and door locks', 'Check that all windows and doors lock securely.', 'Verify all entry points lock properly.', '1. Walk the perimeter. 2. Test each window and door lock. 3. Tighten or replace loose or broken hardware. 4. Fix any that do not latch or lock.', 'safety', 365, 2, 'Weak or broken locks reduce security and invite break-ins.', 'Working locks improve security and peace of mind.', 'Improves security and may lower insurance claims.'),
  ('Inspect home security system', 'Test sensors, keypad, and communication for the security system.', 'Confirm sensors, keypad, and monitoring work.', '1. Arm and disarm the system. 2. Test door and window sensors. 3. Check motion sensors if present. 4. Verify low-battery alerts and replace batteries as needed.', 'safety', 90, 2, 'Faulty sensors or communication can miss intrusions or cause false alarms.', 'A working system deters break-ins and alerts you to problems.', 'Maintains deterrence and reliable monitoring.'),
  ('Replace HVAC air filter', 'Replace the HVAC system air filter to maintain airflow and air quality.', 'Swap the furnace/AC filter every 1–3 months.', '1. Turn off system if recommended. 2. Open filter door and remove old filter. 3. Insert new filter with correct orientation (arrow toward blower). 4. Close door and turn system back on.', 'hvac', 60, 3, 'Dirty filters restrict airflow, strain the system, and worsen indoor air.', 'Clean filters improve efficiency and air quality.', 'Extends equipment life and can lower utility bills.'),
  ('Clean HVAC return vents', 'Clean return air vents and grilles so the system can pull air freely.', 'Vacuum and wipe return vents and grilles.', '1. Remove grilles if possible. 2. Vacuum inside the duct a short way. 3. Wipe grilles with a damp cloth. 4. Reinstall grilles.', 'hvac', 90, 2, 'Clogged returns reduce airflow and make the system work harder.', 'Clean returns improve airflow and efficiency.', 'Supports efficiency and can extend equipment life.'),
  ('Inspect furnace', 'Annual inspection of the furnace for safe and efficient operation.', 'Have the furnace checked once a year.', '1. Schedule a qualified technician. 2. They will check burners, heat exchanger, flue, and safety devices. 3. Replace filter and note any recommended repairs.', 'hvac', 365, 3, 'Unchecked furnaces can develop cracks or blockages leading to CO or fire risk.', 'Annual inspection catches problems before they become dangerous.', 'Reduces CO and fire risk; can prevent costly repairs.'),
  ('Inspect AC unit', 'Annual inspection of the outdoor AC unit and refrigerant system.', 'Have the AC unit inspected once a year.', '1. Schedule an HVAC technician. 2. They will check refrigerant, coils, fan, and electrical. 3. Clear debris from around the unit. 4. Follow any repair recommendations.', 'hvac', 365, 3, 'Skipping inspection can lead to refrigerant leaks, poor cooling, or compressor failure.', 'Regular inspection keeps cooling reliable and efficient.', 'Can prevent major AC replacement costs.'),
  ('Clean AC condenser coils', 'Clean the outdoor condenser coils so the AC can reject heat properly.', 'Clean outdoor coils once a year.', '1. Turn off power to the unit. 2. Remove debris and gently clean fins with a hose or coil cleaner. 3. Straighten bent fins with a fin comb. 4. Restore power.', 'hvac', 365, 2, 'Dirty coils reduce efficiency and can cause overheating or failure.', 'Clean coils improve cooling and efficiency.', 'Can lower bills and extend AC life.'),
  ('Clear AC condensate drain', 'Clear the AC condensate drain line to prevent backups and water damage.', 'Flush or clear the condensate drain quarterly.', '1. Locate the condensate drain and drain pan. 2. Pour a cup of vinegar or use a drain brush through the access. 3. Flush with water. 4. Confirm water flows outside or to a drain.', 'hvac', 90, 3, 'Clogged drains cause water to back up and can damage ceilings or equipment.', 'A clear drain prevents leaks and overflow.', 'Avoids water damage and mold from overflow.'),
  ('Test thermostat', 'Verify the thermostat correctly calls for heat and cool and displays accurately.', 'Confirm thermostat operation and calibration.', '1. Set heat above room temp; confirm furnace runs. 2. Set cool below room temp; confirm AC runs. 3. Check display and batteries. 4. Adjust or replace if inaccurate.', 'hvac', 90, 2, 'A faulty thermostat can cause comfort issues and wasted energy.', 'An accurate thermostat improves comfort and efficiency.', 'Improves comfort and can reduce energy use.'),
  ('Inspect ductwork for leaks', 'Inspect accessible ducts for leaks, gaps, or disconnections.', 'Check ducts for leaks and poor connections.', '1. Access attic or crawlspace ducts. 2. Look for disconnected sections, tears, or unsealed joints. 3. Seal with mastic or metal-backed tape (not standard duct tape). 4. Insulate if needed.', 'hvac', 365, 2, 'Leaky ducts waste energy and reduce comfort.', 'Sealed ducts improve efficiency and even temperatures.', 'Can lower heating and cooling costs.'),
  ('Clean bathroom exhaust fans', 'Clean bathroom exhaust fan grilles and housings to maintain airflow.', 'Clean fan grilles and housing yearly.', '1. Turn off power. 2. Remove grille and vacuum or wash it. 3. Wipe housing and fan blades if accessible. 4. Reinstall grille and restore power.', 'hvac', 365, 2, 'Dirty fans move less air and can contribute to moisture and mold.', 'Clean fans remove moisture and reduce mold risk.', 'Reduces moisture and mold in bathrooms.'),
  ('Clean range hood filter', 'Clean or replace the range hood filter so it captures grease and smoke.', 'Clean or replace the range hood filter quarterly.', '1. Remove the filter per manufacturer instructions. 2. Soak in hot soapy water or run through dishwasher if allowed. 3. Replace if disposable or damaged. 4. Reinstall.', 'hvac', 90, 2, 'Clogged filters reduce capture of smoke and grease; can be a fire hazard.', 'A clean filter improves capture and reduces grease buildup.', 'Improves kitchen air quality and reduces fire risk.'),
  ('Flush water heater', 'Drain sediment from the water heater tank to extend life and efficiency.', 'Drain a few gallons from the tank yearly.', '1. Turn off power or gas and cold supply. 2. Connect hose to drain valve; run to drain or outside. 3. Open drain and a hot tap to allow flow. 4. Flush until water runs clear. 5. Close valve, refill, restore power/gas.', 'plumbing', 365, 3, 'Sediment shortens tank life and can cause noise or overheating.', 'Flushing extends tank life and improves efficiency.', 'Can extend tank life and delay replacement.'),
  ('Test water heater pressure valve', 'Test the temperature and pressure relief (T&P) valve on the water heater.', 'Lift the T&P valve briefly to confirm it operates.', '1. Locate the T&P valve on the tank (top or side). 2. Place a bucket under the discharge pipe. 3. Lift the valve tab briefly; water should discharge then stop when released. 4. If it leaks or does not operate, replace or call a plumber.', 'plumbing', 365, 3, 'A stuck T&P valve can contribute to overpressure and tank failure.', 'A working valve relieves excess pressure safely.', 'Reduces risk of tank rupture and water damage.'),
  ('Inspect plumbing for leaks', 'Check visible pipes, fittings, and fixtures for leaks or moisture.', 'Look for leaks at fixtures and visible pipes.', '1. Check under sinks, around toilets, and at visible pipes. 2. Feel for moisture and look for stains or corrosion. 3. Fix dripping faucets and leaking connections. 4. Note any issues for a plumber if needed.', 'plumbing', 90, 3, 'Unfixed leaks waste water and can cause rot or mold.', 'Catching leaks early limits damage and cost.', 'Avoids water waste and larger repair or mold costs.'),
  ('Clean faucet aerators', 'Remove and clean faucet aerators to restore flow and reduce sediment.', 'Clean aerators on kitchen and bath faucets yearly.', '1. Unscrew the aerator from the faucet tip (use a cloth for grip). 2. Rinse and brush out sediment. 3. Soak in vinegar if mineral buildup. 4. Reinstall and test flow.', 'plumbing', 365, 1, 'Clogged aerators reduce flow and can harbor bacteria.', 'Clean aerators improve flow and water quality at the tap.', 'Improves flow and tap water quality.'),
  ('Check water pressure', 'Check home water pressure and adjust or repair if too high or low.', 'Verify pressure is in a safe, comfortable range.', '1. Use a pressure gauge on an outdoor bib or laundry faucet. 2. Typical target is 40–80 psi. 3. If too high, install or adjust a pressure regulator. 4. If too low, check for leaks or regulator issues.', 'plumbing', 365, 2, 'High pressure stresses pipes and fixtures; low pressure affects use.', 'Proper pressure protects plumbing and improves use.', 'Reduces risk of pipe or fixture damage.'),
  ('Inspect sump pump', 'Inspect the sump pump, pit, and discharge for proper operation.', 'Check sump pump and discharge quarterly.', '1. Ensure pump is upright and cord is secure. 2. Pour water into the pit to trigger the pump. 3. Confirm it runs and discharges outside away from the foundation. 4. Clean the pit and check the check valve.', 'plumbing', 90, 3, 'A failed sump pump can lead to basement flooding during storms.', 'A working pump prevents basement water damage.', 'Avoids basement flooding and water damage.'),
  ('Test sump pump backup', 'Test the sump pump backup (battery or water-powered) if present.', 'Test backup system so it runs when needed.', '1. Locate backup unit. 2. For battery backup, test per manufacturer (often a test button). 3. For water-powered, verify water supply and operation. 4. Replace battery or service as recommended.', 'plumbing', 90, 3, 'Backup failure during a power outage can allow flooding.', 'A working backup provides protection during outages.', 'Reduces flood risk when power is out.'),
  ('Clean gutters', 'Clean leaves and debris from gutters and downspouts so water can flow.', 'Clear gutters and downspouts twice a year.', '1. Use a ladder safely; wear gloves. 2. Remove debris by hand or with a scoop. 3. Flush with a hose and check for leaks. 4. Ensure downspouts direct water away from the foundation.', 'exterior', 182, 3, 'Clogged gutters cause overflow, fascia rot, and foundation water issues.', 'Clear gutters protect the roof and foundation.', 'Prevents fascia, soffit, and foundation damage.'),
  ('Check downspout drainage', 'Confirm downspouts direct water away from the foundation.', 'Verify downspout extensions and grading.', '1. Trace each downspout to where it discharges. 2. Ensure extensions or splash blocks direct water at least several feet from the foundation. 3. Fix or add extensions as needed. 4. Check grading so water does not pool near the house.', 'exterior', 182, 3, 'Water near the foundation can cause basement leaks and settling.', 'Good drainage protects the foundation and basement.', 'Reduces basement moisture and foundation issues.'),
  ('Inspect outdoor hose bibs', 'Inspect outdoor faucets for leaks and proper winterization.', 'Check hose bibs and shutoffs yearly.', '1. Turn on each bib and check for leaks at the spout and connection. 2. Replace washers or bibs if needed. 3. Before winter, shut off interior supply and drain the bib if applicable.', 'exterior', 365, 2, 'Leaking or un-winterized bibs can freeze and burst pipes.', 'Working, winterized bibs prevent freeze damage.', 'Avoids frozen pipe bursts and water damage.'),
  ('Inspect electrical panel', 'Inspect the main electrical panel for signs of trouble and correct labeling.', 'Review panel and breakers yearly.', '1. Turn off power to the panel if doing any work (or hire an electrician). 2. Look for burning smell, corrosion, or warm breakers. 3. Confirm labels match circuits. 4. Tighten loose breakers only if qualified.', 'electrical', 365, 3, 'Overheating or poor connections can cause fire or power issues.', 'A sound panel reduces fire risk and supports reliability.', 'Reduces fire and power failure risk.'),
  ('Test circuit breakers', 'Test that breakers trip and reset correctly under load.', 'Verify breakers function as intended.', '1. Identify a few non-critical circuits. 2. Switch off, then on; confirm power returns. 3. If any breaker will not hold or feels hot, have an electrician evaluate. 4. Do not overload circuits.', 'electrical', 365, 2, 'Faulty breakers may not protect against overload or short circuits.', 'Working breakers protect wiring and appliances.', 'Protects against overload and fire.'),
  ('Replace exterior light bulbs', 'Replace burned-out exterior bulbs to maintain safety and appearance.', 'Replace outdoor bulbs as they burn out.', '1. Turn off power or switch. 2. Replace with the same type and wattage (or approved LED equivalent). 3. Check seals and fixtures for moisture. 4. Restore power.', 'electrical', 365, 1, 'Dark areas reduce security and increase trip hazards.', 'Working lights improve safety and curb appeal.', 'Improves safety and appearance.'),
  ('Clean light fixtures', 'Dust and clean interior and exterior light fixtures for better light and appearance.', 'Clean fixtures to improve light output.', '1. Turn off power. 2. Remove covers or bulbs and dust or wash. 3. Dry thoroughly before reinstalling. 4. Replace any damaged gaskets on outdoor fixtures.', 'electrical', 365, 1, 'Dirty fixtures reduce light and can trap heat.', 'Clean fixtures improve light and longevity.', 'Better light and fixture life.'),
  ('Check outdoor electrical outlets', 'Test GFCI protection and operation of outdoor outlets.', 'Test and secure outdoor outlets yearly.', '1. Confirm outlets are GFCI-protected (test/reset buttons or upstream GFCI). 2. Test with a plug-in tester. 3. Check covers are in place and weatherproof. 4. Repair or replace as needed.', 'electrical', 365, 2, 'Faulty or exposed outdoor outlets increase shock risk.', 'Working, protected outlets are safe for outdoor use.', 'Reduces shock risk outdoors.'),
  ('Inspect roof for damage', 'Inspect roof surface, flashing, and vents for damage or wear.', 'Check roof once a year for damage or wear.', '1. From the ground or safely from a ladder, look for missing or damaged shingles, cracked flashing, or damaged vents. 2. Note any moss, algae, or debris. 3. Schedule repairs with a qualified roofer as needed.', 'exterior', 365, 3, 'Unrepaired roof damage leads to leaks and structural damage.', 'Catching damage early limits leaks and cost.', 'Avoids interior water damage and costly repairs.'),
  ('Inspect attic for leaks', 'Inspect the attic for signs of roof leaks, pests, or insulation issues.', 'Check attic for leaks and insulation quarterly.', '1. Use a flashlight and watch for stains, wet insulation, or daylight. 2. Check around vents, chimneys, and penetrations. 3. Look for pest entry or damage. 4. Address leaks or pests promptly.', 'interior', 90, 3, 'Unnoticed attic leaks cause rot, mold, and insulation damage.', 'Early detection limits water and pest damage.', 'Prevents mold and structural damage.'),
  ('Check foundation for cracks', 'Check foundation walls and slab for new or worsening cracks.', 'Inspect foundation for cracks yearly.', '1. Walk the perimeter and look at visible foundation. 2. Note the size and direction of cracks; photograph. 3. Monitor for widening or moisture. 4. Have significant or active cracks evaluated by a professional.', 'interior', 365, 3, 'Unaddressed foundation issues can worsen and be very costly.', 'Monitoring helps plan repairs before problems grow.', 'Early action can reduce repair cost.'),
  ('Inspect siding', 'Inspect siding for damage, loose pieces, or moisture issues.', 'Check siding condition once a year.', '1. Walk the perimeter and look for cracks, warping, or loose sections. 2. Check around windows and doors for gaps or rot. 3. Note areas that need caulk or repair. 4. Address moisture or pest entry promptly.', 'exterior', 365, 2, 'Damaged siding allows moisture and pests and reduces curb appeal.', 'Good siding protects the structure and looks good.', 'Protects structure and appearance.'),
  ('Inspect windows and caulking', 'Inspect windows and exterior caulking for leaks and deterioration.', 'Check windows and caulk yearly.', '1. Check interior and exterior around each window for drafts or moisture. 2. Inspect caulk and sealant; remove failed caulk and recaulk. 3. Repair or replace damaged seals and hardware.', 'exterior', 365, 2, 'Failed caulk and seals cause drafts, moisture, and energy loss.', 'Good seals improve comfort and efficiency.', 'Reduces drafts and moisture; can lower energy use.'),
  ('Inspect doors and weatherstripping', 'Inspect exterior doors and weatherstripping for fit and wear.', 'Check doors and weatherstripping yearly.', '1. Check each exterior door for gaps, drafts, and damaged weatherstripping. 2. Replace worn threshold or door sweep. 3. Adjust hinges if the door sags. 4. Recauk or seal as needed.', 'exterior', 365, 2, 'Worn seals cause drafts and higher energy bills.', 'Good weatherstripping improves comfort and efficiency.', 'Improves comfort and can lower heating/cooling cost.'),
  ('Power wash exterior surfaces', 'Power wash siding, deck, or walkways to remove dirt and mildew.', 'Power wash siding and hard surfaces yearly.', '1. Use an appropriate pressure (low for wood siding to avoid damage). 2. Work from top down. 3. Use detergent or mildew cleaner where needed. 4. Rinse thoroughly.', 'exterior', 365, 1, 'Built-up dirt and mildew can damage surfaces and look bad.', 'Clean surfaces last longer and look better.', 'Preserves surfaces and curb appeal.'),
  ('Inspect driveway and walkways', 'Inspect driveway and walkways for cracks, heaving, or trip hazards.', 'Check pavement and walkways yearly.', '1. Walk driveway and walkways. 2. Note cracks, heaving, or loose pavers. 3. Fill small cracks; plan repair for larger issues. 4. Keep surfaces clear of moss or ice.', 'exterior', 365, 2, 'Cracks and heaving can worsen and cause trip hazards.', 'Maintained surfaces are safer and last longer.', 'Reduces trip risk and preserves surfaces.'),
  ('Clean and seal deck', 'Clean the deck and apply sealant or stain to protect the wood.', 'Clean and seal or stain the deck yearly.', '1. Sweep and clean the deck; use deck cleaner if needed. 2. Let dry. 3. Apply sealant or stain per product instructions. 4. Allow to cure before use.', 'exterior', 365, 2, 'Unprotected wood can warp, crack, or rot.', 'Sealing extends deck life and appearance.', 'Extends deck life and appearance.'),
  ('Inspect fencing', 'Inspect fence posts, boards, and gates for damage or instability.', 'Check fence condition yearly.', '1. Walk the fence line. 2. Look for loose posts, broken boards, or damaged gates. 3. Tighten hardware and replace damaged sections. 4. Treat or paint wood as needed.', 'exterior', 365, 1, 'Damaged fencing can fall or allow pests and privacy loss.', 'Stable fencing lasts longer and stays secure.', 'Maintains privacy and safety.'),
  ('Clean refrigerator coils', 'Clean the refrigerator condenser coils for efficiency and longevity.', 'Vacuum or brush coils once a year.', '1. Unplug or turn off the refrigerator. 2. Locate coils (rear or front bottom). 3. Use a brush or vacuum to remove dust. 4. Restore power.', 'interior', 365, 2, 'Dirty coils make the fridge work harder and can shorten its life.', 'Clean coils improve efficiency and extend life.', 'Can lower electric use and extend fridge life.'),
  ('Clean garbage disposal', 'Clean the garbage disposal to remove buildup and odors.', 'Run a cleaning cycle monthly.', '1. Do not put hands in the disposal. 2. Run cold water. 3. Drop in ice cubes and a few citrus peels or use disposal cleaner. 4. Run the unit briefly; flush with water.', 'interior', 30, 1, 'Built-up residue causes odors and can affect performance.', 'A clean disposal runs better and smells fresh.', 'Reduces odors and keeps disposal working.'),
  ('Inspect bathroom caulking', 'Inspect and replace failed caulk around tub, shower, and sinks.', 'Check and recaulk as needed yearly.', '1. Look for cracked, peeling, or discolored caulk. 2. Remove old caulk with a tool or knife. 3. Clean and dry the area. 4. Apply new silicone caulk and smooth the bead.', 'interior', 365, 2, 'Failed caulk allows water behind surfaces and causes mold or rot.', 'Good caulk keeps water out and surfaces dry.', 'Prevents water damage and mold.'),
  ('Check tile grout', 'Inspect tile grout for cracks, stains, or missing sections.', 'Inspect and repair grout yearly.', '1. Check grout lines in showers, backsplashes, and floors. 2. Repair cracked or missing grout with grout or epoxy. 3. Consider sealing grout to reduce staining. 4. Fix any loose tiles.', 'interior', 365, 1, 'Damaged grout allows water behind tiles and can cause mold or loosening.', 'Sound grout protects the substrate and looks good.', 'Prevents water intrusion and tile failure.'),
  ('Lubricate door hinges', 'Lubricate interior and exterior door hinges to prevent squeaking and wear.', 'Lubricate hinges yearly.', '1. Open the door and apply a small amount of lubricant (e.g. silicone or light oil) to hinge pins. 2. Wipe excess. 3. Open and close the door a few times to work in the lubricant.', 'interior', 365, 1, 'Dry hinges squeak and can wear out faster.', 'Lubricated hinges operate quietly and last longer.', 'Reduces noise and wear.'),
  ('Test interior doors for sticking', 'Check interior doors for sticking, binding, or misalignment.', 'Test doors and adjust as needed yearly.', '1. Open and close each door. 2. Note any that stick, bind, or do not latch. 3. Tighten hinges or plane/sand the door edge as needed. 4. Adjust strike plates if necessary.', 'interior', 365, 1, 'Sticking doors can damage frames and are a nuisance.', 'Smooth doors operate correctly and last longer.', 'Improves function and prevents frame damage.')
) AS v(title, description, summary, instructions, category, frequency_days, criticality, risks_of_skipping, benefits_of_maintenance, repair_cost_savings)
WHERE NOT EXISTS (
  SELECT 1 FROM public.maintenance_templates mt
  WHERE lower(trim(mt.title)) = lower(trim(v.title))
);
