// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://drshvrukkavtpsprfcbc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRyc2h2cnVra2F2dHBzcHJmY2JjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2MDQ5NDgsImV4cCI6MjA2ODE4MDk0OH0.yR61yCPJvqs_TVi5hmdmT7CF0QJKqr_lWR5TX25EwTc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});